config/routes.rb
Rails.application.routes.draw do
  resources :nota
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/notum.rb
class Notum < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notas
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :moderador, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nota_controller.rb
class NotaController < ApplicationController
  before_action :set_notum, only: %i[ show edit update destroy ]

  # GET /nota or /nota.json
  def index
    @nota = Notum.all
  end

  # GET /nota/1 or /nota/1.json
  def show
  end

  # GET /nota/new
  def new
    @notum = current_user.notas.new
  end

  # GET /nota/1/edit
  def edit
  end

  # POST /nota or /nota.json
  def create
    @notum = Notum.new(notum_params)

    respond_to do |format|
      if @notum.save
        format.html { redirect_to notum_url(@notum), notice: "Notum was successfully created." }
        format.json { render :show, status: :created, location: @notum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota/1 or /nota/1.json
  def update
    respond_to do |format|
      if @notum.update(notum_params)
        format.html { redirect_to notum_url(@notum), notice: "Notum was successfully updated." }
        format.json { render :show, status: :ok, location: @notum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota/1 or /nota/1.json
  def destroy
    @notum.destroy

    respond_to do |format|
      format.html { redirect_to nota_url, notice: "Notum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notum
      @notum = Notum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notum_params
      params.require(:notum).permit(:user_id, :conteudo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nota_helper.rb
module NotaHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nota/_form.html.erb
<%= form_with(model: notum) do |form| %>
  <% if notum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notum.errors.count, "error") %> prohibited this notum from being saved:</h2>

      <ul>
        <% notum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :conteudo, style: "display: block" %>
    <%= form.text_area :conteudo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nota/_notum.html.erb
<div id="<%= dom_id notum %>">
  <p>
    <strong>User:</strong>
    <%= notum.user_id %>
  </p>

  <p>
    <strong>Conteudo:</strong>
    <%= notum.conteudo %>
  </p>

</div>

app/views/nota/edit.html.erb
<h1>Editing notum</h1>

<%= render "form", notum: @notum %>

<br>

<div>
  <%= link_to "Show this notum", @notum %> |
  <%= link_to "Back to nota", nota_path %>
</div>

app/views/nota/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Nota</h1>

<div id="nota">
  <% @nota.each do |notum| %>
    <%= render notum %>
    <p>
      <%= link_to "Show this notum", notum %>
    </p>
  <% end %>
</div>

<%= link_to "New notum", new_notum_path %>

app/views/nota/new.html.erb
<h1>New notum</h1>

<%= render "form", notum: @notum %>

<br>

<div>
  <%= link_to "Back to nota", nota_path %>
</div>

app/views/nota/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notum %>

<div>
  <%= link_to "Edit this notum", edit_notum_path(@notum) %> |
  <%= link_to "Back to nota", nota_path %>

  <%= button_to "Destroy this notum", @notum, method: :delete %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if current_user %>
    <h1> Vocé é um <%= current_user.role %> </h1>
    <% if current_user.admin? %>
        <span> Há <%= User.count %> usuarios </span>
    <% end %>
    <p> Bem vindo <%= current_user.email %></p>
    <p>
        Você logou com sucesso, agora pode interagir com o projeto.
    </p>
    <%= link_to "Deslogar", destroy_user_session_path, 'data-turbo-method': :delete%>
<% else %>
    <p> Você não está logado. </p>
    <p>
        <%= link_to "Logar", new_user_session_path %>
        <br>
        <%= link_to "Cadastrar", new_user_registration_path %>
    </p>
<% end %>